package io.pleo.antaeus.models

enum class InvoiceStatus {
    PENDING,
    PAID,
    PENDING_INSUFICIENTCASH,
    PENDING_INVALIDCUSTOMER,
    PENDING_INVALIDCURRENCY,
    PENDING_NETWORKUNAVAILABLE
}
